# name: try 
# key: mytry 
# --

try {
    $1
} catch (const std::exception &e) {
  std::cerr << e.what() << std::endl;

}
